Feature/801 deployment
mit-submit/A2rchi pull request #79
Opened 2023-09-27 13:06 UTC by julius-heitkoetter

Created scripts for the 8.01 deployment. Basically just copied all the prod stuff over, replaced `prod` with `prod-801` and then double checked that all the replacements were correct.

2023-09-27 13:08 UTC, julius-heitkoetter commented
Do not merge until #77 is resolved

2023-09-29 00:45 UTC, mdr223 requested changes
Left two comments, one of which requires a change for correctness. Otherwise it all looks good!

2023-09-29 00:45 UTC, mdr223 commented on .github/workflows/prod-801-ci-cd.yaml
> +          ssh submit-t3desk 'bash -s' < ${{ github.workspace }}/deploy/prod/prod-801-install.sh
Need to change `deploy/prod/` --> `deploy/prod-801/`

2023-09-29 00:45 UTC, mdr223 commented on config/prod-801-config.yaml
> +    - submit.list
Does this class use `SubMIT` or is it intentional to leave this in?

2023-09-29 02:27 UTC, mdr223 commented on config/prod-801-config.yaml
> +    - submit.list
Removing for now, can always add back.

2023-09-29 02:31 UTC, mdr223 approved these changes
Made minor tweaks; updated docker-compose to mount 801 content which is now on t3desk

2023-09-29 02:31 UTC, merged